### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by xiaoyuanzh** [hjkuijf/ALGLIB#1]
Hi how to compile it in linux.
I mean, where is the makefile or cmakelists staffs?

**Comment by a2nath** [comment]
I'm getting an error too. In the instructions it doesn't really talk about building the library itself, which I am assuming will get rid of the "setglobalthreading" and "parallel not defined" errors from demo.cpp.

**Comment by hjkuijf** [comment]
This repository contains a copy of ALGLIB version 3.4.0, with build instructions for MeVisLab. You can build the makefile (ALGLIB.pro) with the MeVisLab ToolRunner or QMake. But note that this is specifically designed to be used with MeVisLab, a "modular framework for image processing research and development with a special focus on medical imaging" (https://www.mevislab.de/).

If you just want to use ALGLIB, go to: https://www.alglib.net/
